### ISSUE TITLE
Xarray dependencies not connected to metocean-stats

### ISSUE THREAD

**Issue by mcarvajalino** [MET-OM/metocean-stats#36]
Hi,

Great work with the stats module!. I just installed it via mamba (miniforge 3) but got a small problem trying to reproduce the "100-yr return period map (NORA3) from the "read the docs". It seems that xarray requires both netcdf4 and pydap as dependencies, but they are not hardwired in the metocean-stats module (see the attached screenshot). 

One can solve it easily by installing netcdf4 and pydap manually in the environment. But it would be good that you include it in the dependencies of metocean-stats directly and avoid the user-fix.
![image](https://github.com/user-attachments/assets/64bcfbe7-2341-4c1e-bf34-c21d8b0de0af)

**Comment by KonstantinChri** [comment]
Hi mcarvajalino, 
Thank you very much for informing about this issue. 
I have now updated the environment file in the latest version (v1.0.3) to contain netcdf4 and pydap.
