### ISSUE TITLE
Missing definition 'get_joint_2D_contour'

### ISSUE THREAD

**Issue by alexeagray** [MET-OM/metocean-stats#76]
get_joint_2D_contour called by plots.extreme.plot_joint_2D_contour, but is not defined anywhere.

**Comment by KonstantinChri** [comment]
Hi, Thanks for informing about this issue. The get_joint_2D_contour function (which uses virocon) is now added in stats. However, for joint Hs-Tp contours, we mainly use the plots.extreme.plot_joint_distribution_Hs_Tp.
